# Generated by Django 5.1 on 2024-08-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_about_alter_experience_options_experience_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
