# Generated by Django 5.1 on 2024-08-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_experience_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='position',
            field=models.CharField(max_length=200),
        ),
    ]
