# Generated by Django 5.1 on 2024-08-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_about_options_alter_about_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-created_at'], 'verbose_name': 'About'},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='is_active',
            new_name='active',
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(),
        ),
    ]
